# Generated by Django 4.2.10 on 2026-02-03 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='待分类文本')),
                ('predicted_category', models.CharField(max_length=100, verbose_name='预测分类')),
                ('confidence', models.FloatField(verbose_name='置信度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='分类时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '分类结果',
                'verbose_name_plural': '分类结果',
            },
        ),
        migrations.CreateModel(
            name='BatchClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('total_count', models.IntegerField(verbose_name='总条数')),
                ('success_count', models.IntegerField(verbose_name='成功条数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '批量分类记录',
                'verbose_name_plural': '批量分类记录',
            },
        ),
    ]
