# Generated by Django 4.2 on 2026-05-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchclassification',
            name='model_used',
            field=models.CharField(default='albert', max_length=50, verbose_name='使用模型'),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='model_used',
            field=models.CharField(default='albert', max_length=50, verbose_name='使用模型'),
        ),
    ]
