# Generated by Django 4.2 on 2026-05-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_batchclassification_model_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchclassification',
            name='elapsed_ms',
            field=models.IntegerField(default=0, verbose_name='总耗时(ms)'),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='elapsed_ms',
            field=models.IntegerField(default=0, verbose_name='推理耗时(ms)'),
        ),
    ]
