# Generated by Django 4.2 on 2026-05-20 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_batchclassification_elapsed_ms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchClassificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField(verbose_name='行号')),
                ('text', models.TextField(verbose_name='文本')),
                ('predicted_category', models.CharField(max_length=100, verbose_name='预测分类')),
                ('confidence', models.FloatField(verbose_name='置信度')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='classifier.batchclassification', verbose_name='所属批次')),
            ],
            options={
                'verbose_name': '批量分类明细',
                'verbose_name_plural': '批量分类明细',
                'ordering': ['batch_id', 'row_index'],
            },
        ),
        migrations.AddIndex(
            model_name='batchclassificationitem',
            index=models.Index(fields=['batch', 'row_index'], name='classifier__batch_i_51704a_idx'),
        ),
    ]
