# Generated by Django 4.2 on 2026-04-30 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_count', models.PositiveIntegerField(default=1, verbose_name='阅读次数')),
                ('first_read_at', models.DateTimeField(auto_now_add=True, verbose_name='首次阅读')),
                ('last_read_at', models.DateTimeField(auto_now=True, verbose_name='最近阅读')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='news.news', verbose_name='新闻')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '阅读历史',
                'verbose_name_plural': '阅读历史',
                'ordering': ['-last_read_at'],
            },
        ),
        migrations.AddIndex(
            model_name='readinghistory',
            index=models.Index(fields=['user', '-last_read_at'], name='accounts_re_user_id_c0f7e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='readinghistory',
            unique_together={('user', 'news')},
        ),
    ]
